apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
spec:
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      containers:
        - name: hello-world
          image: zakariaalla/helloworld-java:v1
          command: ["java", "Hello"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
